/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DomainModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DomainModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cElementsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cElementsTypeParserRuleCall_0_0 = (RuleCall)cElementsAssignment_0.eContents().get(0);
		private final Assignment cApisAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cApisRestAPIParserRuleCall_1_0 = (RuleCall)cApisAssignment_1.eContents().get(0);
		
		//DomainModel:
		//	elements+=Type* apis+=RestAPI*;
		@Override public ParserRule getRule() { return rule; }

		//elements+=Type* apis+=RestAPI*
		public Group getGroup() { return cGroup; }

		//elements+=Type*
		public Assignment getElementsAssignment_0() { return cElementsAssignment_0; }

		//Type
		public RuleCall getElementsTypeParserRuleCall_0_0() { return cElementsTypeParserRuleCall_0_0; }

		//apis+=RestAPI*
		public Assignment getApisAssignment_1() { return cApisAssignment_1; }

		//RestAPI
		public RuleCall getApisRestAPIParserRuleCall_1_0() { return cApisRestAPIParserRuleCall_1_0; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimitiveTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDataModelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRestModelParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMappingModelParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Type:
		//	PrimitiveType | DataModel | RestModel | MappingModel;
		@Override public ParserRule getRule() { return rule; }

		//PrimitiveType | DataModel | RestModel | MappingModel
		public Alternatives getAlternatives() { return cAlternatives; }

		//PrimitiveType
		public RuleCall getPrimitiveTypeParserRuleCall_0() { return cPrimitiveTypeParserRuleCall_0; }

		//DataModel
		public RuleCall getDataModelParserRuleCall_1() { return cDataModelParserRuleCall_1; }

		//RestModel
		public RuleCall getRestModelParserRuleCall_2() { return cRestModelParserRuleCall_2; }

		//MappingModel
		public RuleCall getMappingModelParserRuleCall_3() { return cMappingModelParserRuleCall_3; }
	}

	public class RestAPIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RestAPI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cResourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cResourceResourceParserRuleCall_0_0 = (RuleCall)cResourceAssignment_0.eContents().get(0);
		private final Assignment cServiceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cServiceServiceParserRuleCall_1_0 = (RuleCall)cServiceAssignment_1.eContents().get(0);
		private final Assignment cDaoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDaoDataAccessObjectParserRuleCall_2_0 = (RuleCall)cDaoAssignment_2.eContents().get(0);
		
		//RestAPI:
		//	resource=Resource service+=Service* dao+=DataAccessObject*;
		@Override public ParserRule getRule() { return rule; }

		//resource=Resource service+=Service* dao+=DataAccessObject*
		public Group getGroup() { return cGroup; }

		//resource=Resource
		public Assignment getResourceAssignment_0() { return cResourceAssignment_0; }

		//Resource
		public RuleCall getResourceResourceParserRuleCall_0_0() { return cResourceResourceParserRuleCall_0_0; }

		//service+=Service*
		public Assignment getServiceAssignment_1() { return cServiceAssignment_1; }

		//Service
		public RuleCall getServiceServiceParserRuleCall_1_0() { return cServiceServiceParserRuleCall_1_0; }

		//dao+=DataAccessObject*
		public Assignment getDaoAssignment_2() { return cDaoAssignment_2; }

		//DataAccessObject
		public RuleCall getDaoDataAccessObjectParserRuleCall_2_0() { return cDaoDataAccessObjectParserRuleCall_2_0; }
	}

	public class PrimitiveTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimitiveType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrimitiveTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//PrimitiveType:
		//	"primitiveType" name=ID;
		@Override public ParserRule getRule() { return rule; }

		//"primitiveType" name=ID
		public Group getGroup() { return cGroup; }

		//"primitiveType"
		public Keyword getPrimitiveTypeKeyword_0() { return cPrimitiveTypeKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class DataModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DataModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeDataModelCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeDataModelIDTerminalRuleCall_2_1_0_1 = (RuleCall)cSuperTypeDataModelCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeaturesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFeaturesFeatureParserRuleCall_4_0 = (RuleCall)cFeaturesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DataModel:
		//	"dataModel" name=ID ("extends" superType=[DataModel])? "{" features+=Feature* "}";
		@Override public ParserRule getRule() { return rule; }

		//"dataModel" name=ID ("extends" superType=[DataModel])? "{" features+=Feature* "}"
		public Group getGroup() { return cGroup; }

		//"dataModel"
		public Keyword getDataModelKeyword_0() { return cDataModelKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" superType=[DataModel])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//superType=[DataModel]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }

		//[DataModel]
		public CrossReference getSuperTypeDataModelCrossReference_2_1_0() { return cSuperTypeDataModelCrossReference_2_1_0; }

		//ID
		public RuleCall getSuperTypeDataModelIDTerminalRuleCall_2_1_0_1() { return cSuperTypeDataModelIDTerminalRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_4() { return cFeaturesAssignment_4; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_4_0() { return cFeaturesFeatureParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class RestModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RestModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRestModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeRestModelCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeRestModelIDTerminalRuleCall_2_1_0_1 = (RuleCall)cSuperTypeRestModelCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeaturesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFeaturesFeatureParserRuleCall_4_0 = (RuleCall)cFeaturesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RestModel:
		//	"restModel" name=ID ("extends" superType=[RestModel])? "{" features+=Feature* "}";
		@Override public ParserRule getRule() { return rule; }

		//"restModel" name=ID ("extends" superType=[RestModel])? "{" features+=Feature* "}"
		public Group getGroup() { return cGroup; }

		//"restModel"
		public Keyword getRestModelKeyword_0() { return cRestModelKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" superType=[RestModel])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//superType=[RestModel]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }

		//[RestModel]
		public CrossReference getSuperTypeRestModelCrossReference_2_1_0() { return cSuperTypeRestModelCrossReference_2_1_0; }

		//ID
		public RuleCall getSuperTypeRestModelIDTerminalRuleCall_2_1_0_1() { return cSuperTypeRestModelIDTerminalRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_4() { return cFeaturesAssignment_4; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_4_0() { return cFeaturesFeatureParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class MappingModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MappingModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMappingModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTransformationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTransformationTransformationParserRuleCall_3_0 = (RuleCall)cTransformationAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MappingModel:
		//	"mappingModel" name=ID "{" transformation+=Transformation* "}";
		@Override public ParserRule getRule() { return rule; }

		//"mappingModel" name=ID "{" transformation+=Transformation* "}"
		public Group getGroup() { return cGroup; }

		//"mappingModel"
		public Keyword getMappingModelKeyword_0() { return cMappingModelKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//transformation+=Transformation*
		public Assignment getTransformationAssignment_3() { return cTransformationAssignment_3; }

		//Transformation
		public RuleCall getTransformationTransformationParserRuleCall_3_0() { return cTransformationTransformationParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class TransformationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transformation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDataModelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cDataModelDataModelCrossReference_1_0 = (CrossReference)cDataModelAssignment_1.eContents().get(0);
		private final RuleCall cDataModelDataModelIDTerminalRuleCall_1_0_1 = (RuleCall)cDataModelDataModelCrossReference_1_0.eContents().get(1);
		private final Keyword cLessThanSignEqualsSignGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRestModelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cRestModelRestModelCrossReference_3_0 = (CrossReference)cRestModelAssignment_3.eContents().get(0);
		private final RuleCall cRestModelRestModelIDTerminalRuleCall_3_0_1 = (RuleCall)cRestModelRestModelCrossReference_3_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Transformation:
		//	"(" dataModel=[DataModel] "<=>" restModel=[RestModel] ")";
		@Override public ParserRule getRule() { return rule; }

		//"(" dataModel=[DataModel] "<=>" restModel=[RestModel] ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//dataModel=[DataModel]
		public Assignment getDataModelAssignment_1() { return cDataModelAssignment_1; }

		//[DataModel]
		public CrossReference getDataModelDataModelCrossReference_1_0() { return cDataModelDataModelCrossReference_1_0; }

		//ID
		public RuleCall getDataModelDataModelIDTerminalRuleCall_1_0_1() { return cDataModelDataModelIDTerminalRuleCall_1_0_1; }

		//"<=>"
		public Keyword getLessThanSignEqualsSignGreaterThanSignKeyword_2() { return cLessThanSignEqualsSignGreaterThanSignKeyword_2; }

		//restModel=[RestModel]
		public Assignment getRestModelAssignment_3() { return cRestModelAssignment_3; }

		//[RestModel]
		public CrossReference getRestModelRestModelCrossReference_3_0() { return cRestModelRestModelCrossReference_3_0; }

		//ID
		public RuleCall getRestModelRestModelIDTerminalRuleCall_3_0_1() { return cRestModelRestModelIDTerminalRuleCall_3_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cManyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cManyManyKeyword_0_0 = (Keyword)cManyAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTypeTypeCrossReference_3_0 = (CrossReference)cTypeAssignment_3.eContents().get(0);
		private final RuleCall cTypeTypeIDTerminalRuleCall_3_0_1 = (RuleCall)cTypeTypeCrossReference_3_0.eContents().get(1);
		
		//Feature:
		//	many?="many"? name=ID ":" type=[Type];
		@Override public ParserRule getRule() { return rule; }

		//many?="many"? name=ID ":" type=[Type]
		public Group getGroup() { return cGroup; }

		//many?="many"?
		public Assignment getManyAssignment_0() { return cManyAssignment_0; }

		//"many"
		public Keyword getManyManyKeyword_0_0() { return cManyManyKeyword_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//type=[Type]
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//[Type]
		public CrossReference getTypeTypeCrossReference_3_0() { return cTypeTypeCrossReference_3_0; }

		//ID
		public RuleCall getTypeTypeIDTerminalRuleCall_3_0_1() { return cTypeTypeIDTerminalRuleCall_3_0_1; }
	}

	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCreateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCreateRestModelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cCreateRestModelRestModelCrossReference_4_0 = (CrossReference)cCreateRestModelAssignment_4.eContents().get(0);
		private final RuleCall cCreateRestModelRestModelIDTerminalRuleCall_4_0_1 = (RuleCall)cCreateRestModelRestModelCrossReference_4_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cThrowsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cException1Assignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cException1RestExceptionParserRuleCall_7_0 = (RuleCall)cException1Assignment_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCreateMethodAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCreateMethodJavaMethodParserRuleCall_9_0 = (RuleCall)cCreateMethodAssignment_9.eContents().get(0);
		private final Keyword cReturnKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cCreatedRestModelAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cCreatedRestModelRestModelCrossReference_11_0 = (CrossReference)cCreatedRestModelAssignment_11.eContents().get(0);
		private final RuleCall cCreatedRestModelRestModelIDTerminalRuleCall_11_0_1 = (RuleCall)cCreatedRestModelRestModelCrossReference_11_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cFindKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cLeftParenthesisKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cFindbyAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cFindbyINTEGERTerminalRuleCall_15_0 = (RuleCall)cFindbyAssignment_15.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cThrowsKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cException2Assignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cException2RestExceptionParserRuleCall_18_0 = (RuleCall)cException2Assignment_18.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cFindMethodAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cFindMethodJavaMethodParserRuleCall_20_0 = (RuleCall)cFindMethodAssignment_20.eContents().get(0);
		private final Keyword cReturnKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cFoundRestModelAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final CrossReference cFoundRestModelRestModelCrossReference_22_0 = (CrossReference)cFoundRestModelAssignment_22.eContents().get(0);
		private final RuleCall cFoundRestModelRestModelIDTerminalRuleCall_22_0_1 = (RuleCall)cFoundRestModelRestModelCrossReference_22_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cUpdateKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cLeftParenthesisKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Assignment cUpdatebyAssignment_26 = (Assignment)cGroup.eContents().get(26);
		private final RuleCall cUpdatebyINTEGERTerminalRuleCall_26_0 = (RuleCall)cUpdatebyAssignment_26.eContents().get(0);
		private final Keyword cCommaKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Assignment cUpdateRestModelAssignment_28 = (Assignment)cGroup.eContents().get(28);
		private final CrossReference cUpdateRestModelRestModelCrossReference_28_0 = (CrossReference)cUpdateRestModelAssignment_28.eContents().get(0);
		private final RuleCall cUpdateRestModelRestModelIDTerminalRuleCall_28_0_1 = (RuleCall)cUpdateRestModelRestModelCrossReference_28_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Keyword cThrowsKeyword_30 = (Keyword)cGroup.eContents().get(30);
		private final Assignment cException3Assignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cException3RestExceptionParserRuleCall_31_0 = (RuleCall)cException3Assignment_31.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_32 = (Keyword)cGroup.eContents().get(32);
		private final Assignment cUpdateMethodAssignment_33 = (Assignment)cGroup.eContents().get(33);
		private final RuleCall cUpdateMethodJavaMethodParserRuleCall_33_0 = (RuleCall)cUpdateMethodAssignment_33.eContents().get(0);
		private final Keyword cReturnKeyword_34 = (Keyword)cGroup.eContents().get(34);
		private final Assignment cUpdatedRestModelAssignment_35 = (Assignment)cGroup.eContents().get(35);
		private final CrossReference cUpdatedRestModelRestModelCrossReference_35_0 = (CrossReference)cUpdatedRestModelAssignment_35.eContents().get(0);
		private final RuleCall cUpdatedRestModelRestModelIDTerminalRuleCall_35_0_1 = (RuleCall)cUpdatedRestModelRestModelCrossReference_35_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_36 = (Keyword)cGroup.eContents().get(36);
		private final Keyword cDeleteKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Keyword cLeftParenthesisKeyword_38 = (Keyword)cGroup.eContents().get(38);
		private final Assignment cDeletebyAssignment_39 = (Assignment)cGroup.eContents().get(39);
		private final RuleCall cDeletebyINTEGERTerminalRuleCall_39_0 = (RuleCall)cDeletebyAssignment_39.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_40 = (Keyword)cGroup.eContents().get(40);
		private final Keyword cThrowsKeyword_41 = (Keyword)cGroup.eContents().get(41);
		private final Assignment cException4Assignment_42 = (Assignment)cGroup.eContents().get(42);
		private final RuleCall cException4RestExceptionParserRuleCall_42_0 = (RuleCall)cException4Assignment_42.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_43 = (Keyword)cGroup.eContents().get(43);
		private final Assignment cDeleteMethodAssignment_44 = (Assignment)cGroup.eContents().get(44);
		private final RuleCall cDeleteMethodJavaMethodParserRuleCall_44_0 = (RuleCall)cDeleteMethodAssignment_44.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_45 = (Keyword)cGroup.eContents().get(45);
		
		//Resource:
		//	"Resource" name=ID "create" "(" createRestModel=[RestModel] ")" "throws" exception1=RestException "{"
		//	createMethod=JavaMethod "return" createdRestModel=[RestModel] "}" "find" "(" findby=INTEGER ")" "throws"
		//	exception2=RestException "{" findMethod=JavaMethod "return" foundRestModel=[RestModel] "}" "update" "("
		//	updateby=INTEGER "," updateRestModel=[RestModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
		//	"return" updatedRestModel=[RestModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
		//	deleteMethod=JavaMethod "}";
		@Override public ParserRule getRule() { return rule; }

		//"Resource" name=ID "create" "(" createRestModel=[RestModel] ")" "throws" exception1=RestException "{"
		//createMethod=JavaMethod "return" createdRestModel=[RestModel] "}" "find" "(" findby=INTEGER ")" "throws"
		//exception2=RestException "{" findMethod=JavaMethod "return" foundRestModel=[RestModel] "}" "update" "("
		//updateby=INTEGER "," updateRestModel=[RestModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
		//"return" updatedRestModel=[RestModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
		//deleteMethod=JavaMethod "}"
		public Group getGroup() { return cGroup; }

		//"Resource"
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"create"
		public Keyword getCreateKeyword_2() { return cCreateKeyword_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }

		//createRestModel=[RestModel]
		public Assignment getCreateRestModelAssignment_4() { return cCreateRestModelAssignment_4; }

		//[RestModel]
		public CrossReference getCreateRestModelRestModelCrossReference_4_0() { return cCreateRestModelRestModelCrossReference_4_0; }

		//ID
		public RuleCall getCreateRestModelRestModelIDTerminalRuleCall_4_0_1() { return cCreateRestModelRestModelIDTerminalRuleCall_4_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }

		//"throws"
		public Keyword getThrowsKeyword_6() { return cThrowsKeyword_6; }

		//exception1=RestException
		public Assignment getException1Assignment_7() { return cException1Assignment_7; }

		//RestException
		public RuleCall getException1RestExceptionParserRuleCall_7_0() { return cException1RestExceptionParserRuleCall_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }

		//createMethod=JavaMethod
		public Assignment getCreateMethodAssignment_9() { return cCreateMethodAssignment_9; }

		//JavaMethod
		public RuleCall getCreateMethodJavaMethodParserRuleCall_9_0() { return cCreateMethodJavaMethodParserRuleCall_9_0; }

		//"return"
		public Keyword getReturnKeyword_10() { return cReturnKeyword_10; }

		//createdRestModel=[RestModel]
		public Assignment getCreatedRestModelAssignment_11() { return cCreatedRestModelAssignment_11; }

		//[RestModel]
		public CrossReference getCreatedRestModelRestModelCrossReference_11_0() { return cCreatedRestModelRestModelCrossReference_11_0; }

		//ID
		public RuleCall getCreatedRestModelRestModelIDTerminalRuleCall_11_0_1() { return cCreatedRestModelRestModelIDTerminalRuleCall_11_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"find"
		public Keyword getFindKeyword_13() { return cFindKeyword_13; }

		//"("
		public Keyword getLeftParenthesisKeyword_14() { return cLeftParenthesisKeyword_14; }

		//findby=INTEGER
		public Assignment getFindbyAssignment_15() { return cFindbyAssignment_15; }

		//INTEGER
		public RuleCall getFindbyINTEGERTerminalRuleCall_15_0() { return cFindbyINTEGERTerminalRuleCall_15_0; }

		//")"
		public Keyword getRightParenthesisKeyword_16() { return cRightParenthesisKeyword_16; }

		//"throws"
		public Keyword getThrowsKeyword_17() { return cThrowsKeyword_17; }

		//exception2=RestException
		public Assignment getException2Assignment_18() { return cException2Assignment_18; }

		//RestException
		public RuleCall getException2RestExceptionParserRuleCall_18_0() { return cException2RestExceptionParserRuleCall_18_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_19() { return cLeftCurlyBracketKeyword_19; }

		//findMethod=JavaMethod
		public Assignment getFindMethodAssignment_20() { return cFindMethodAssignment_20; }

		//JavaMethod
		public RuleCall getFindMethodJavaMethodParserRuleCall_20_0() { return cFindMethodJavaMethodParserRuleCall_20_0; }

		//"return"
		public Keyword getReturnKeyword_21() { return cReturnKeyword_21; }

		//foundRestModel=[RestModel]
		public Assignment getFoundRestModelAssignment_22() { return cFoundRestModelAssignment_22; }

		//[RestModel]
		public CrossReference getFoundRestModelRestModelCrossReference_22_0() { return cFoundRestModelRestModelCrossReference_22_0; }

		//ID
		public RuleCall getFoundRestModelRestModelIDTerminalRuleCall_22_0_1() { return cFoundRestModelRestModelIDTerminalRuleCall_22_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_23() { return cRightCurlyBracketKeyword_23; }

		//"update"
		public Keyword getUpdateKeyword_24() { return cUpdateKeyword_24; }

		//"("
		public Keyword getLeftParenthesisKeyword_25() { return cLeftParenthesisKeyword_25; }

		//updateby=INTEGER
		public Assignment getUpdatebyAssignment_26() { return cUpdatebyAssignment_26; }

		//INTEGER
		public RuleCall getUpdatebyINTEGERTerminalRuleCall_26_0() { return cUpdatebyINTEGERTerminalRuleCall_26_0; }

		//","
		public Keyword getCommaKeyword_27() { return cCommaKeyword_27; }

		//updateRestModel=[RestModel]
		public Assignment getUpdateRestModelAssignment_28() { return cUpdateRestModelAssignment_28; }

		//[RestModel]
		public CrossReference getUpdateRestModelRestModelCrossReference_28_0() { return cUpdateRestModelRestModelCrossReference_28_0; }

		//ID
		public RuleCall getUpdateRestModelRestModelIDTerminalRuleCall_28_0_1() { return cUpdateRestModelRestModelIDTerminalRuleCall_28_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_29() { return cRightParenthesisKeyword_29; }

		//"throws"
		public Keyword getThrowsKeyword_30() { return cThrowsKeyword_30; }

		//exception3=RestException
		public Assignment getException3Assignment_31() { return cException3Assignment_31; }

		//RestException
		public RuleCall getException3RestExceptionParserRuleCall_31_0() { return cException3RestExceptionParserRuleCall_31_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_32() { return cLeftCurlyBracketKeyword_32; }

		//updateMethod=JavaMethod
		public Assignment getUpdateMethodAssignment_33() { return cUpdateMethodAssignment_33; }

		//JavaMethod
		public RuleCall getUpdateMethodJavaMethodParserRuleCall_33_0() { return cUpdateMethodJavaMethodParserRuleCall_33_0; }

		//"return"
		public Keyword getReturnKeyword_34() { return cReturnKeyword_34; }

		//updatedRestModel=[RestModel]
		public Assignment getUpdatedRestModelAssignment_35() { return cUpdatedRestModelAssignment_35; }

		//[RestModel]
		public CrossReference getUpdatedRestModelRestModelCrossReference_35_0() { return cUpdatedRestModelRestModelCrossReference_35_0; }

		//ID
		public RuleCall getUpdatedRestModelRestModelIDTerminalRuleCall_35_0_1() { return cUpdatedRestModelRestModelIDTerminalRuleCall_35_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_36() { return cRightCurlyBracketKeyword_36; }

		//"delete"
		public Keyword getDeleteKeyword_37() { return cDeleteKeyword_37; }

		//"("
		public Keyword getLeftParenthesisKeyword_38() { return cLeftParenthesisKeyword_38; }

		//deleteby=INTEGER
		public Assignment getDeletebyAssignment_39() { return cDeletebyAssignment_39; }

		//INTEGER
		public RuleCall getDeletebyINTEGERTerminalRuleCall_39_0() { return cDeletebyINTEGERTerminalRuleCall_39_0; }

		//")"
		public Keyword getRightParenthesisKeyword_40() { return cRightParenthesisKeyword_40; }

		//"throws"
		public Keyword getThrowsKeyword_41() { return cThrowsKeyword_41; }

		//exception4=RestException
		public Assignment getException4Assignment_42() { return cException4Assignment_42; }

		//RestException
		public RuleCall getException4RestExceptionParserRuleCall_42_0() { return cException4RestExceptionParserRuleCall_42_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_43() { return cLeftCurlyBracketKeyword_43; }

		//deleteMethod=JavaMethod
		public Assignment getDeleteMethodAssignment_44() { return cDeleteMethodAssignment_44; }

		//JavaMethod
		public RuleCall getDeleteMethodJavaMethodParserRuleCall_44_0() { return cDeleteMethodJavaMethodParserRuleCall_44_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_45() { return cRightCurlyBracketKeyword_45; }
	}

	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Service");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCreateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCreateDataModelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cCreateDataModelDataModelCrossReference_4_0 = (CrossReference)cCreateDataModelAssignment_4.eContents().get(0);
		private final RuleCall cCreateDataModelDataModelIDTerminalRuleCall_4_0_1 = (RuleCall)cCreateDataModelDataModelCrossReference_4_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cThrowsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cException1Assignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cException1RestExceptionParserRuleCall_7_0 = (RuleCall)cException1Assignment_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCreateMethodAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCreateMethodJavaMethodParserRuleCall_9_0 = (RuleCall)cCreateMethodAssignment_9.eContents().get(0);
		private final Keyword cReturnKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cCreatedDataModelAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cCreatedDataModelDataModelCrossReference_11_0 = (CrossReference)cCreatedDataModelAssignment_11.eContents().get(0);
		private final RuleCall cCreatedDataModelDataModelIDTerminalRuleCall_11_0_1 = (RuleCall)cCreatedDataModelDataModelCrossReference_11_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cFindKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cLeftParenthesisKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cFindbyAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cFindbyINTEGERTerminalRuleCall_15_0 = (RuleCall)cFindbyAssignment_15.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cThrowsKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cException2Assignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cException2RestExceptionParserRuleCall_18_0 = (RuleCall)cException2Assignment_18.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cFindMethodAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cFindMethodJavaMethodParserRuleCall_20_0 = (RuleCall)cFindMethodAssignment_20.eContents().get(0);
		private final Keyword cReturnKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cFoundDataModelAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final CrossReference cFoundDataModelDataModelCrossReference_22_0 = (CrossReference)cFoundDataModelAssignment_22.eContents().get(0);
		private final RuleCall cFoundDataModelDataModelIDTerminalRuleCall_22_0_1 = (RuleCall)cFoundDataModelDataModelCrossReference_22_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cUpdateKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cLeftParenthesisKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Assignment cUpdatebyAssignment_26 = (Assignment)cGroup.eContents().get(26);
		private final RuleCall cUpdatebyINTEGERTerminalRuleCall_26_0 = (RuleCall)cUpdatebyAssignment_26.eContents().get(0);
		private final Keyword cCommaKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Assignment cUpdateDataModelAssignment_28 = (Assignment)cGroup.eContents().get(28);
		private final CrossReference cUpdateDataModelDataModelCrossReference_28_0 = (CrossReference)cUpdateDataModelAssignment_28.eContents().get(0);
		private final RuleCall cUpdateDataModelDataModelIDTerminalRuleCall_28_0_1 = (RuleCall)cUpdateDataModelDataModelCrossReference_28_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Keyword cThrowsKeyword_30 = (Keyword)cGroup.eContents().get(30);
		private final Assignment cException3Assignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cException3RestExceptionParserRuleCall_31_0 = (RuleCall)cException3Assignment_31.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_32 = (Keyword)cGroup.eContents().get(32);
		private final Assignment cUpdateMethodAssignment_33 = (Assignment)cGroup.eContents().get(33);
		private final RuleCall cUpdateMethodJavaMethodParserRuleCall_33_0 = (RuleCall)cUpdateMethodAssignment_33.eContents().get(0);
		private final Keyword cReturnKeyword_34 = (Keyword)cGroup.eContents().get(34);
		private final Assignment cUpdatedDataModelAssignment_35 = (Assignment)cGroup.eContents().get(35);
		private final CrossReference cUpdatedDataModelDataModelCrossReference_35_0 = (CrossReference)cUpdatedDataModelAssignment_35.eContents().get(0);
		private final RuleCall cUpdatedDataModelDataModelIDTerminalRuleCall_35_0_1 = (RuleCall)cUpdatedDataModelDataModelCrossReference_35_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_36 = (Keyword)cGroup.eContents().get(36);
		private final Keyword cDeleteKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Keyword cLeftParenthesisKeyword_38 = (Keyword)cGroup.eContents().get(38);
		private final Assignment cDeletebyAssignment_39 = (Assignment)cGroup.eContents().get(39);
		private final RuleCall cDeletebyINTEGERTerminalRuleCall_39_0 = (RuleCall)cDeletebyAssignment_39.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_40 = (Keyword)cGroup.eContents().get(40);
		private final Keyword cThrowsKeyword_41 = (Keyword)cGroup.eContents().get(41);
		private final Assignment cException4Assignment_42 = (Assignment)cGroup.eContents().get(42);
		private final RuleCall cException4RestExceptionParserRuleCall_42_0 = (RuleCall)cException4Assignment_42.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_43 = (Keyword)cGroup.eContents().get(43);
		private final Assignment cDeleteMethodAssignment_44 = (Assignment)cGroup.eContents().get(44);
		private final RuleCall cDeleteMethodJavaMethodParserRuleCall_44_0 = (RuleCall)cDeleteMethodAssignment_44.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_45 = (Keyword)cGroup.eContents().get(45);
		
		//Service:
		//	"Service" name=ID "create" "(" createDataModel=[DataModel] ")" "throws" exception1=RestException "{"
		//	createMethod=JavaMethod "return" createdDataModel=[DataModel] "}" "find" "(" findby=INTEGER ")" "throws"
		//	exception2=RestException "{" findMethod=JavaMethod "return" foundDataModel=[DataModel] "}" "update" "("
		//	updateby=INTEGER "," updateDataModel=[DataModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
		//	"return" updatedDataModel=[DataModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
		//	deleteMethod=JavaMethod "}";
		@Override public ParserRule getRule() { return rule; }

		//"Service" name=ID "create" "(" createDataModel=[DataModel] ")" "throws" exception1=RestException "{"
		//createMethod=JavaMethod "return" createdDataModel=[DataModel] "}" "find" "(" findby=INTEGER ")" "throws"
		//exception2=RestException "{" findMethod=JavaMethod "return" foundDataModel=[DataModel] "}" "update" "("
		//updateby=INTEGER "," updateDataModel=[DataModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
		//"return" updatedDataModel=[DataModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
		//deleteMethod=JavaMethod "}"
		public Group getGroup() { return cGroup; }

		//"Service"
		public Keyword getServiceKeyword_0() { return cServiceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"create"
		public Keyword getCreateKeyword_2() { return cCreateKeyword_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }

		//createDataModel=[DataModel]
		public Assignment getCreateDataModelAssignment_4() { return cCreateDataModelAssignment_4; }

		//[DataModel]
		public CrossReference getCreateDataModelDataModelCrossReference_4_0() { return cCreateDataModelDataModelCrossReference_4_0; }

		//ID
		public RuleCall getCreateDataModelDataModelIDTerminalRuleCall_4_0_1() { return cCreateDataModelDataModelIDTerminalRuleCall_4_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }

		//"throws"
		public Keyword getThrowsKeyword_6() { return cThrowsKeyword_6; }

		//exception1=RestException
		public Assignment getException1Assignment_7() { return cException1Assignment_7; }

		//RestException
		public RuleCall getException1RestExceptionParserRuleCall_7_0() { return cException1RestExceptionParserRuleCall_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }

		//createMethod=JavaMethod
		public Assignment getCreateMethodAssignment_9() { return cCreateMethodAssignment_9; }

		//JavaMethod
		public RuleCall getCreateMethodJavaMethodParserRuleCall_9_0() { return cCreateMethodJavaMethodParserRuleCall_9_0; }

		//"return"
		public Keyword getReturnKeyword_10() { return cReturnKeyword_10; }

		//createdDataModel=[DataModel]
		public Assignment getCreatedDataModelAssignment_11() { return cCreatedDataModelAssignment_11; }

		//[DataModel]
		public CrossReference getCreatedDataModelDataModelCrossReference_11_0() { return cCreatedDataModelDataModelCrossReference_11_0; }

		//ID
		public RuleCall getCreatedDataModelDataModelIDTerminalRuleCall_11_0_1() { return cCreatedDataModelDataModelIDTerminalRuleCall_11_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"find"
		public Keyword getFindKeyword_13() { return cFindKeyword_13; }

		//"("
		public Keyword getLeftParenthesisKeyword_14() { return cLeftParenthesisKeyword_14; }

		//findby=INTEGER
		public Assignment getFindbyAssignment_15() { return cFindbyAssignment_15; }

		//INTEGER
		public RuleCall getFindbyINTEGERTerminalRuleCall_15_0() { return cFindbyINTEGERTerminalRuleCall_15_0; }

		//")"
		public Keyword getRightParenthesisKeyword_16() { return cRightParenthesisKeyword_16; }

		//"throws"
		public Keyword getThrowsKeyword_17() { return cThrowsKeyword_17; }

		//exception2=RestException
		public Assignment getException2Assignment_18() { return cException2Assignment_18; }

		//RestException
		public RuleCall getException2RestExceptionParserRuleCall_18_0() { return cException2RestExceptionParserRuleCall_18_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_19() { return cLeftCurlyBracketKeyword_19; }

		//findMethod=JavaMethod
		public Assignment getFindMethodAssignment_20() { return cFindMethodAssignment_20; }

		//JavaMethod
		public RuleCall getFindMethodJavaMethodParserRuleCall_20_0() { return cFindMethodJavaMethodParserRuleCall_20_0; }

		//"return"
		public Keyword getReturnKeyword_21() { return cReturnKeyword_21; }

		//foundDataModel=[DataModel]
		public Assignment getFoundDataModelAssignment_22() { return cFoundDataModelAssignment_22; }

		//[DataModel]
		public CrossReference getFoundDataModelDataModelCrossReference_22_0() { return cFoundDataModelDataModelCrossReference_22_0; }

		//ID
		public RuleCall getFoundDataModelDataModelIDTerminalRuleCall_22_0_1() { return cFoundDataModelDataModelIDTerminalRuleCall_22_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_23() { return cRightCurlyBracketKeyword_23; }

		//"update"
		public Keyword getUpdateKeyword_24() { return cUpdateKeyword_24; }

		//"("
		public Keyword getLeftParenthesisKeyword_25() { return cLeftParenthesisKeyword_25; }

		//updateby=INTEGER
		public Assignment getUpdatebyAssignment_26() { return cUpdatebyAssignment_26; }

		//INTEGER
		public RuleCall getUpdatebyINTEGERTerminalRuleCall_26_0() { return cUpdatebyINTEGERTerminalRuleCall_26_0; }

		//","
		public Keyword getCommaKeyword_27() { return cCommaKeyword_27; }

		//updateDataModel=[DataModel]
		public Assignment getUpdateDataModelAssignment_28() { return cUpdateDataModelAssignment_28; }

		//[DataModel]
		public CrossReference getUpdateDataModelDataModelCrossReference_28_0() { return cUpdateDataModelDataModelCrossReference_28_0; }

		//ID
		public RuleCall getUpdateDataModelDataModelIDTerminalRuleCall_28_0_1() { return cUpdateDataModelDataModelIDTerminalRuleCall_28_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_29() { return cRightParenthesisKeyword_29; }

		//"throws"
		public Keyword getThrowsKeyword_30() { return cThrowsKeyword_30; }

		//exception3=RestException
		public Assignment getException3Assignment_31() { return cException3Assignment_31; }

		//RestException
		public RuleCall getException3RestExceptionParserRuleCall_31_0() { return cException3RestExceptionParserRuleCall_31_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_32() { return cLeftCurlyBracketKeyword_32; }

		//updateMethod=JavaMethod
		public Assignment getUpdateMethodAssignment_33() { return cUpdateMethodAssignment_33; }

		//JavaMethod
		public RuleCall getUpdateMethodJavaMethodParserRuleCall_33_0() { return cUpdateMethodJavaMethodParserRuleCall_33_0; }

		//"return"
		public Keyword getReturnKeyword_34() { return cReturnKeyword_34; }

		//updatedDataModel=[DataModel]
		public Assignment getUpdatedDataModelAssignment_35() { return cUpdatedDataModelAssignment_35; }

		//[DataModel]
		public CrossReference getUpdatedDataModelDataModelCrossReference_35_0() { return cUpdatedDataModelDataModelCrossReference_35_0; }

		//ID
		public RuleCall getUpdatedDataModelDataModelIDTerminalRuleCall_35_0_1() { return cUpdatedDataModelDataModelIDTerminalRuleCall_35_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_36() { return cRightCurlyBracketKeyword_36; }

		//"delete"
		public Keyword getDeleteKeyword_37() { return cDeleteKeyword_37; }

		//"("
		public Keyword getLeftParenthesisKeyword_38() { return cLeftParenthesisKeyword_38; }

		//deleteby=INTEGER
		public Assignment getDeletebyAssignment_39() { return cDeletebyAssignment_39; }

		//INTEGER
		public RuleCall getDeletebyINTEGERTerminalRuleCall_39_0() { return cDeletebyINTEGERTerminalRuleCall_39_0; }

		//")"
		public Keyword getRightParenthesisKeyword_40() { return cRightParenthesisKeyword_40; }

		//"throws"
		public Keyword getThrowsKeyword_41() { return cThrowsKeyword_41; }

		//exception4=RestException
		public Assignment getException4Assignment_42() { return cException4Assignment_42; }

		//RestException
		public RuleCall getException4RestExceptionParserRuleCall_42_0() { return cException4RestExceptionParserRuleCall_42_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_43() { return cLeftCurlyBracketKeyword_43; }

		//deleteMethod=JavaMethod
		public Assignment getDeleteMethodAssignment_44() { return cDeleteMethodAssignment_44; }

		//JavaMethod
		public RuleCall getDeleteMethodJavaMethodParserRuleCall_44_0() { return cDeleteMethodJavaMethodParserRuleCall_44_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_45() { return cRightCurlyBracketKeyword_45; }
	}

	public class DataAccessObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DataAccessObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDAOKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCreateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCreateDataModelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cCreateDataModelDataModelCrossReference_4_0 = (CrossReference)cCreateDataModelAssignment_4.eContents().get(0);
		private final RuleCall cCreateDataModelDataModelIDTerminalRuleCall_4_0_1 = (RuleCall)cCreateDataModelDataModelCrossReference_4_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cThrowsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cException1Assignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cException1RestExceptionParserRuleCall_7_0 = (RuleCall)cException1Assignment_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCreateMethodAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCreateMethodJavaMethodParserRuleCall_9_0 = (RuleCall)cCreateMethodAssignment_9.eContents().get(0);
		private final Keyword cReturnKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cCreatedDataModelAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cCreatedDataModelDataModelCrossReference_11_0 = (CrossReference)cCreatedDataModelAssignment_11.eContents().get(0);
		private final RuleCall cCreatedDataModelDataModelIDTerminalRuleCall_11_0_1 = (RuleCall)cCreatedDataModelDataModelCrossReference_11_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cFindKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cLeftParenthesisKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cFindbyAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cFindbyINTEGERTerminalRuleCall_15_0 = (RuleCall)cFindbyAssignment_15.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cThrowsKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cException2Assignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cException2RestExceptionParserRuleCall_18_0 = (RuleCall)cException2Assignment_18.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cFindMethodAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cFindMethodJavaMethodParserRuleCall_20_0 = (RuleCall)cFindMethodAssignment_20.eContents().get(0);
		private final Keyword cReturnKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cFoundDataModelAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final CrossReference cFoundDataModelDataModelCrossReference_22_0 = (CrossReference)cFoundDataModelAssignment_22.eContents().get(0);
		private final RuleCall cFoundDataModelDataModelIDTerminalRuleCall_22_0_1 = (RuleCall)cFoundDataModelDataModelCrossReference_22_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cUpdateKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cLeftParenthesisKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Assignment cUpdatebyAssignment_26 = (Assignment)cGroup.eContents().get(26);
		private final RuleCall cUpdatebyINTEGERTerminalRuleCall_26_0 = (RuleCall)cUpdatebyAssignment_26.eContents().get(0);
		private final Keyword cCommaKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Assignment cUpdateDataModelAssignment_28 = (Assignment)cGroup.eContents().get(28);
		private final CrossReference cUpdateDataModelDataModelCrossReference_28_0 = (CrossReference)cUpdateDataModelAssignment_28.eContents().get(0);
		private final RuleCall cUpdateDataModelDataModelIDTerminalRuleCall_28_0_1 = (RuleCall)cUpdateDataModelDataModelCrossReference_28_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Keyword cThrowsKeyword_30 = (Keyword)cGroup.eContents().get(30);
		private final Assignment cException3Assignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cException3RestExceptionParserRuleCall_31_0 = (RuleCall)cException3Assignment_31.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_32 = (Keyword)cGroup.eContents().get(32);
		private final Assignment cUpdateMethodAssignment_33 = (Assignment)cGroup.eContents().get(33);
		private final RuleCall cUpdateMethodJavaMethodParserRuleCall_33_0 = (RuleCall)cUpdateMethodAssignment_33.eContents().get(0);
		private final Keyword cReturnKeyword_34 = (Keyword)cGroup.eContents().get(34);
		private final Assignment cUpdatedDataModelAssignment_35 = (Assignment)cGroup.eContents().get(35);
		private final CrossReference cUpdatedDataModelDataModelCrossReference_35_0 = (CrossReference)cUpdatedDataModelAssignment_35.eContents().get(0);
		private final RuleCall cUpdatedDataModelDataModelIDTerminalRuleCall_35_0_1 = (RuleCall)cUpdatedDataModelDataModelCrossReference_35_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_36 = (Keyword)cGroup.eContents().get(36);
		private final Keyword cDeleteKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Keyword cLeftParenthesisKeyword_38 = (Keyword)cGroup.eContents().get(38);
		private final Assignment cDeletebyAssignment_39 = (Assignment)cGroup.eContents().get(39);
		private final RuleCall cDeletebyINTEGERTerminalRuleCall_39_0 = (RuleCall)cDeletebyAssignment_39.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_40 = (Keyword)cGroup.eContents().get(40);
		private final Keyword cThrowsKeyword_41 = (Keyword)cGroup.eContents().get(41);
		private final Assignment cException4Assignment_42 = (Assignment)cGroup.eContents().get(42);
		private final RuleCall cException4RestExceptionParserRuleCall_42_0 = (RuleCall)cException4Assignment_42.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_43 = (Keyword)cGroup.eContents().get(43);
		private final Assignment cDeleteMethodAssignment_44 = (Assignment)cGroup.eContents().get(44);
		private final RuleCall cDeleteMethodJavaMethodParserRuleCall_44_0 = (RuleCall)cDeleteMethodAssignment_44.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_45 = (Keyword)cGroup.eContents().get(45);
		
		//DataAccessObject:
		//	"DAO" name=ID "create" "(" createDataModel=[DataModel] ")" "throws" exception1=RestException "{"
		//	createMethod=JavaMethod "return" createdDataModel=[DataModel] "}" "find" "(" findby=INTEGER ")" "throws"
		//	exception2=RestException "{" findMethod=JavaMethod "return" foundDataModel=[DataModel] "}" "update" "("
		//	updateby=INTEGER "," updateDataModel=[DataModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
		//	"return" updatedDataModel=[DataModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
		//	deleteMethod=JavaMethod "}";
		@Override public ParserRule getRule() { return rule; }

		//"DAO" name=ID "create" "(" createDataModel=[DataModel] ")" "throws" exception1=RestException "{" createMethod=JavaMethod
		//"return" createdDataModel=[DataModel] "}" "find" "(" findby=INTEGER ")" "throws" exception2=RestException "{"
		//findMethod=JavaMethod "return" foundDataModel=[DataModel] "}" "update" "(" updateby=INTEGER ","
		//updateDataModel=[DataModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod "return"
		//updatedDataModel=[DataModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
		//deleteMethod=JavaMethod "}"
		public Group getGroup() { return cGroup; }

		//"DAO"
		public Keyword getDAOKeyword_0() { return cDAOKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"create"
		public Keyword getCreateKeyword_2() { return cCreateKeyword_2; }

		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }

		//createDataModel=[DataModel]
		public Assignment getCreateDataModelAssignment_4() { return cCreateDataModelAssignment_4; }

		//[DataModel]
		public CrossReference getCreateDataModelDataModelCrossReference_4_0() { return cCreateDataModelDataModelCrossReference_4_0; }

		//ID
		public RuleCall getCreateDataModelDataModelIDTerminalRuleCall_4_0_1() { return cCreateDataModelDataModelIDTerminalRuleCall_4_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }

		//"throws"
		public Keyword getThrowsKeyword_6() { return cThrowsKeyword_6; }

		//exception1=RestException
		public Assignment getException1Assignment_7() { return cException1Assignment_7; }

		//RestException
		public RuleCall getException1RestExceptionParserRuleCall_7_0() { return cException1RestExceptionParserRuleCall_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }

		//createMethod=JavaMethod
		public Assignment getCreateMethodAssignment_9() { return cCreateMethodAssignment_9; }

		//JavaMethod
		public RuleCall getCreateMethodJavaMethodParserRuleCall_9_0() { return cCreateMethodJavaMethodParserRuleCall_9_0; }

		//"return"
		public Keyword getReturnKeyword_10() { return cReturnKeyword_10; }

		//createdDataModel=[DataModel]
		public Assignment getCreatedDataModelAssignment_11() { return cCreatedDataModelAssignment_11; }

		//[DataModel]
		public CrossReference getCreatedDataModelDataModelCrossReference_11_0() { return cCreatedDataModelDataModelCrossReference_11_0; }

		//ID
		public RuleCall getCreatedDataModelDataModelIDTerminalRuleCall_11_0_1() { return cCreatedDataModelDataModelIDTerminalRuleCall_11_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"find"
		public Keyword getFindKeyword_13() { return cFindKeyword_13; }

		//"("
		public Keyword getLeftParenthesisKeyword_14() { return cLeftParenthesisKeyword_14; }

		//findby=INTEGER
		public Assignment getFindbyAssignment_15() { return cFindbyAssignment_15; }

		//INTEGER
		public RuleCall getFindbyINTEGERTerminalRuleCall_15_0() { return cFindbyINTEGERTerminalRuleCall_15_0; }

		//")"
		public Keyword getRightParenthesisKeyword_16() { return cRightParenthesisKeyword_16; }

		//"throws"
		public Keyword getThrowsKeyword_17() { return cThrowsKeyword_17; }

		//exception2=RestException
		public Assignment getException2Assignment_18() { return cException2Assignment_18; }

		//RestException
		public RuleCall getException2RestExceptionParserRuleCall_18_0() { return cException2RestExceptionParserRuleCall_18_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_19() { return cLeftCurlyBracketKeyword_19; }

		//findMethod=JavaMethod
		public Assignment getFindMethodAssignment_20() { return cFindMethodAssignment_20; }

		//JavaMethod
		public RuleCall getFindMethodJavaMethodParserRuleCall_20_0() { return cFindMethodJavaMethodParserRuleCall_20_0; }

		//"return"
		public Keyword getReturnKeyword_21() { return cReturnKeyword_21; }

		//foundDataModel=[DataModel]
		public Assignment getFoundDataModelAssignment_22() { return cFoundDataModelAssignment_22; }

		//[DataModel]
		public CrossReference getFoundDataModelDataModelCrossReference_22_0() { return cFoundDataModelDataModelCrossReference_22_0; }

		//ID
		public RuleCall getFoundDataModelDataModelIDTerminalRuleCall_22_0_1() { return cFoundDataModelDataModelIDTerminalRuleCall_22_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_23() { return cRightCurlyBracketKeyword_23; }

		//"update"
		public Keyword getUpdateKeyword_24() { return cUpdateKeyword_24; }

		//"("
		public Keyword getLeftParenthesisKeyword_25() { return cLeftParenthesisKeyword_25; }

		//updateby=INTEGER
		public Assignment getUpdatebyAssignment_26() { return cUpdatebyAssignment_26; }

		//INTEGER
		public RuleCall getUpdatebyINTEGERTerminalRuleCall_26_0() { return cUpdatebyINTEGERTerminalRuleCall_26_0; }

		//","
		public Keyword getCommaKeyword_27() { return cCommaKeyword_27; }

		//updateDataModel=[DataModel]
		public Assignment getUpdateDataModelAssignment_28() { return cUpdateDataModelAssignment_28; }

		//[DataModel]
		public CrossReference getUpdateDataModelDataModelCrossReference_28_0() { return cUpdateDataModelDataModelCrossReference_28_0; }

		//ID
		public RuleCall getUpdateDataModelDataModelIDTerminalRuleCall_28_0_1() { return cUpdateDataModelDataModelIDTerminalRuleCall_28_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_29() { return cRightParenthesisKeyword_29; }

		//"throws"
		public Keyword getThrowsKeyword_30() { return cThrowsKeyword_30; }

		//exception3=RestException
		public Assignment getException3Assignment_31() { return cException3Assignment_31; }

		//RestException
		public RuleCall getException3RestExceptionParserRuleCall_31_0() { return cException3RestExceptionParserRuleCall_31_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_32() { return cLeftCurlyBracketKeyword_32; }

		//updateMethod=JavaMethod
		public Assignment getUpdateMethodAssignment_33() { return cUpdateMethodAssignment_33; }

		//JavaMethod
		public RuleCall getUpdateMethodJavaMethodParserRuleCall_33_0() { return cUpdateMethodJavaMethodParserRuleCall_33_0; }

		//"return"
		public Keyword getReturnKeyword_34() { return cReturnKeyword_34; }

		//updatedDataModel=[DataModel]
		public Assignment getUpdatedDataModelAssignment_35() { return cUpdatedDataModelAssignment_35; }

		//[DataModel]
		public CrossReference getUpdatedDataModelDataModelCrossReference_35_0() { return cUpdatedDataModelDataModelCrossReference_35_0; }

		//ID
		public RuleCall getUpdatedDataModelDataModelIDTerminalRuleCall_35_0_1() { return cUpdatedDataModelDataModelIDTerminalRuleCall_35_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_36() { return cRightCurlyBracketKeyword_36; }

		//"delete"
		public Keyword getDeleteKeyword_37() { return cDeleteKeyword_37; }

		//"("
		public Keyword getLeftParenthesisKeyword_38() { return cLeftParenthesisKeyword_38; }

		//deleteby=INTEGER
		public Assignment getDeletebyAssignment_39() { return cDeletebyAssignment_39; }

		//INTEGER
		public RuleCall getDeletebyINTEGERTerminalRuleCall_39_0() { return cDeletebyINTEGERTerminalRuleCall_39_0; }

		//")"
		public Keyword getRightParenthesisKeyword_40() { return cRightParenthesisKeyword_40; }

		//"throws"
		public Keyword getThrowsKeyword_41() { return cThrowsKeyword_41; }

		//exception4=RestException
		public Assignment getException4Assignment_42() { return cException4Assignment_42; }

		//RestException
		public RuleCall getException4RestExceptionParserRuleCall_42_0() { return cException4RestExceptionParserRuleCall_42_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_43() { return cLeftCurlyBracketKeyword_43; }

		//deleteMethod=JavaMethod
		public Assignment getDeleteMethodAssignment_44() { return cDeleteMethodAssignment_44; }

		//JavaMethod
		public RuleCall getDeleteMethodJavaMethodParserRuleCall_44_0() { return cDeleteMethodJavaMethodParserRuleCall_44_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_45() { return cRightCurlyBracketKeyword_45; }
	}

	public class RestExceptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RestException");
		private final Assignment cStatusCodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStatusCodeRestStatusCodeEnumRuleCall_0 = (RuleCall)cStatusCodeAssignment.eContents().get(0);
		
		//RestException:
		//	statusCode=RestStatusCode;
		@Override public ParserRule getRule() { return rule; }

		//statusCode=RestStatusCode
		public Assignment getStatusCodeAssignment() { return cStatusCodeAssignment; }

		//RestStatusCode
		public RuleCall getStatusCodeRestStatusCodeEnumRuleCall_0() { return cStatusCodeRestStatusCodeEnumRuleCall_0; }
	}

	public class JavaMethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JavaMethod");
		private final Assignment cCodeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCodeSTRINGTerminalRuleCall_0 = (RuleCall)cCodeAssignment.eContents().get(0);
		
		//JavaMethod: //will be expanded later to include actual Java syntax
		//	code=STRING;
		@Override public ParserRule getRule() { return rule; }

		////will be expanded later to include actual Java syntax
		//code=STRING
		public Assignment getCodeAssignment() { return cCodeAssignment; }

		//STRING
		public RuleCall getCodeSTRINGTerminalRuleCall_0() { return cCodeSTRINGTerminalRuleCall_0; }
	}
	
	
	public class RestStatusCodeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "RestStatusCode");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINFORMATIONALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINFORMATIONALINFORMATIONALKeyword_0_0 = (Keyword)cINFORMATIONALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSUCCESSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSUCCESSSUCCESSKeyword_1_0 = (Keyword)cSUCCESSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cREDIRECTIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cREDIRECTIONREDIRECTIONKeyword_2_0 = (Keyword)cREDIRECTIONEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cCLIENT_ERROREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cCLIENT_ERRORCLIENT_ERRORKeyword_3_0 = (Keyword)cCLIENT_ERROREnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cSERVER_ERROREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cSERVER_ERRORSERVER_ERRORKeyword_4_0 = (Keyword)cSERVER_ERROREnumLiteralDeclaration_4.eContents().get(0);
		
		//enum RestStatusCode:
		//	INFORMATIONAL | SUCCESS | REDIRECTION | CLIENT_ERROR | SERVER_ERROR;
		public EnumRule getRule() { return rule; }

		//INFORMATIONAL | SUCCESS | REDIRECTION | CLIENT_ERROR | SERVER_ERROR
		public Alternatives getAlternatives() { return cAlternatives; }

		//INFORMATIONAL
		public EnumLiteralDeclaration getINFORMATIONALEnumLiteralDeclaration_0() { return cINFORMATIONALEnumLiteralDeclaration_0; }

		//"INFORMATIONAL"
		public Keyword getINFORMATIONALINFORMATIONALKeyword_0_0() { return cINFORMATIONALINFORMATIONALKeyword_0_0; }

		//SUCCESS
		public EnumLiteralDeclaration getSUCCESSEnumLiteralDeclaration_1() { return cSUCCESSEnumLiteralDeclaration_1; }

		//"SUCCESS"
		public Keyword getSUCCESSSUCCESSKeyword_1_0() { return cSUCCESSSUCCESSKeyword_1_0; }

		//REDIRECTION
		public EnumLiteralDeclaration getREDIRECTIONEnumLiteralDeclaration_2() { return cREDIRECTIONEnumLiteralDeclaration_2; }

		//"REDIRECTION"
		public Keyword getREDIRECTIONREDIRECTIONKeyword_2_0() { return cREDIRECTIONREDIRECTIONKeyword_2_0; }

		//CLIENT_ERROR
		public EnumLiteralDeclaration getCLIENT_ERROREnumLiteralDeclaration_3() { return cCLIENT_ERROREnumLiteralDeclaration_3; }

		//"CLIENT_ERROR"
		public Keyword getCLIENT_ERRORCLIENT_ERRORKeyword_3_0() { return cCLIENT_ERRORCLIENT_ERRORKeyword_3_0; }

		//SERVER_ERROR
		public EnumLiteralDeclaration getSERVER_ERROREnumLiteralDeclaration_4() { return cSERVER_ERROREnumLiteralDeclaration_4; }

		//"SERVER_ERROR"
		public Keyword getSERVER_ERRORSERVER_ERRORKeyword_4_0() { return cSERVER_ERRORSERVER_ERRORKeyword_4_0; }
	}
	
	private final DomainModelElements pDomainModel;
	private final TypeElements pType;
	private final RestAPIElements pRestAPI;
	private final PrimitiveTypeElements pPrimitiveType;
	private final DataModelElements pDataModel;
	private final RestModelElements pRestModel;
	private final MappingModelElements pMappingModel;
	private final TransformationElements pTransformation;
	private final FeatureElements pFeature;
	private final ResourceElements pResource;
	private final ServiceElements pService;
	private final DataAccessObjectElements pDataAccessObject;
	private final RestExceptionElements pRestException;
	private final TerminalRule tINTEGER;
	private final RestStatusCodeElements unknownRuleRestStatusCode;
	private final JavaMethodElements pJavaMethod;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomainModel = new DomainModelElements();
		this.pType = new TypeElements();
		this.pRestAPI = new RestAPIElements();
		this.pPrimitiveType = new PrimitiveTypeElements();
		this.pDataModel = new DataModelElements();
		this.pRestModel = new RestModelElements();
		this.pMappingModel = new MappingModelElements();
		this.pTransformation = new TransformationElements();
		this.pFeature = new FeatureElements();
		this.pResource = new ResourceElements();
		this.pService = new ServiceElements();
		this.pDataAccessObject = new DataAccessObjectElements();
		this.pRestException = new RestExceptionElements();
		this.tINTEGER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INTEGER");
		this.unknownRuleRestStatusCode = new RestStatusCodeElements();
		this.pJavaMethod = new JavaMethodElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DomainModel:
	//	elements+=Type* apis+=RestAPI*;
	public DomainModelElements getDomainModelAccess() {
		return pDomainModel;
	}
	
	public ParserRule getDomainModelRule() {
		return getDomainModelAccess().getRule();
	}

	//Type:
	//	PrimitiveType | DataModel | RestModel | MappingModel;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//RestAPI:
	//	resource=Resource service+=Service* dao+=DataAccessObject*;
	public RestAPIElements getRestAPIAccess() {
		return pRestAPI;
	}
	
	public ParserRule getRestAPIRule() {
		return getRestAPIAccess().getRule();
	}

	//PrimitiveType:
	//	"primitiveType" name=ID;
	public PrimitiveTypeElements getPrimitiveTypeAccess() {
		return pPrimitiveType;
	}
	
	public ParserRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}

	//DataModel:
	//	"dataModel" name=ID ("extends" superType=[DataModel])? "{" features+=Feature* "}";
	public DataModelElements getDataModelAccess() {
		return pDataModel;
	}
	
	public ParserRule getDataModelRule() {
		return getDataModelAccess().getRule();
	}

	//RestModel:
	//	"restModel" name=ID ("extends" superType=[RestModel])? "{" features+=Feature* "}";
	public RestModelElements getRestModelAccess() {
		return pRestModel;
	}
	
	public ParserRule getRestModelRule() {
		return getRestModelAccess().getRule();
	}

	//MappingModel:
	//	"mappingModel" name=ID "{" transformation+=Transformation* "}";
	public MappingModelElements getMappingModelAccess() {
		return pMappingModel;
	}
	
	public ParserRule getMappingModelRule() {
		return getMappingModelAccess().getRule();
	}

	//Transformation:
	//	"(" dataModel=[DataModel] "<=>" restModel=[RestModel] ")";
	public TransformationElements getTransformationAccess() {
		return pTransformation;
	}
	
	public ParserRule getTransformationRule() {
		return getTransformationAccess().getRule();
	}

	//Feature:
	//	many?="many"? name=ID ":" type=[Type];
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//Resource:
	//	"Resource" name=ID "create" "(" createRestModel=[RestModel] ")" "throws" exception1=RestException "{"
	//	createMethod=JavaMethod "return" createdRestModel=[RestModel] "}" "find" "(" findby=INTEGER ")" "throws"
	//	exception2=RestException "{" findMethod=JavaMethod "return" foundRestModel=[RestModel] "}" "update" "("
	//	updateby=INTEGER "," updateRestModel=[RestModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
	//	"return" updatedRestModel=[RestModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
	//	deleteMethod=JavaMethod "}";
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}

	//Service:
	//	"Service" name=ID "create" "(" createDataModel=[DataModel] ")" "throws" exception1=RestException "{"
	//	createMethod=JavaMethod "return" createdDataModel=[DataModel] "}" "find" "(" findby=INTEGER ")" "throws"
	//	exception2=RestException "{" findMethod=JavaMethod "return" foundDataModel=[DataModel] "}" "update" "("
	//	updateby=INTEGER "," updateDataModel=[DataModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
	//	"return" updatedDataModel=[DataModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
	//	deleteMethod=JavaMethod "}";
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}

	//DataAccessObject:
	//	"DAO" name=ID "create" "(" createDataModel=[DataModel] ")" "throws" exception1=RestException "{"
	//	createMethod=JavaMethod "return" createdDataModel=[DataModel] "}" "find" "(" findby=INTEGER ")" "throws"
	//	exception2=RestException "{" findMethod=JavaMethod "return" foundDataModel=[DataModel] "}" "update" "("
	//	updateby=INTEGER "," updateDataModel=[DataModel] ")" "throws" exception3=RestException "{" updateMethod=JavaMethod
	//	"return" updatedDataModel=[DataModel] "}" "delete" "(" deleteby=INTEGER ")" "throws" exception4=RestException "{"
	//	deleteMethod=JavaMethod "}";
	public DataAccessObjectElements getDataAccessObjectAccess() {
		return pDataAccessObject;
	}
	
	public ParserRule getDataAccessObjectRule() {
		return getDataAccessObjectAccess().getRule();
	}

	//RestException:
	//	statusCode=RestStatusCode;
	public RestExceptionElements getRestExceptionAccess() {
		return pRestException;
	}
	
	public ParserRule getRestExceptionRule() {
		return getRestExceptionAccess().getRule();
	}

	//terminal INTEGER:
	//	"0".."9"+;
	public TerminalRule getINTEGERRule() {
		return tINTEGER;
	} 

	//enum RestStatusCode:
	//	INFORMATIONAL | SUCCESS | REDIRECTION | CLIENT_ERROR | SERVER_ERROR;
	public RestStatusCodeElements getRestStatusCodeAccess() {
		return unknownRuleRestStatusCode;
	}
	
	public EnumRule getRestStatusCodeRule() {
		return getRestStatusCodeAccess().getRule();
	}

	//JavaMethod: //will be expanded later to include actual Java syntax
	//	code=STRING;
	public JavaMethodElements getJavaMethodAccess() {
		return pJavaMethod;
	}
	
	public ParserRule getJavaMethodRule() {
		return getJavaMethodAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
